parameters:
  - name: id
    in: path
    required: true
    schema:
      type: string
    description: Ingress ID
get:
  summary: Get ingress by ID
  description: Returns a single money ingress by ID
  operationId: getIngress
  tags:
    - Ingresses
  responses:
    '200':
      description: Ingress found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Ingress.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '500':
      $ref: ../components/responses/500.yaml
