parameters:
  - name: id
    in: path
    required: true
    schema:
      type: string
    description: Ingress ID
get:
  summary: Get ingress by ID
  description: Returns a single money ingress by ID
  operationId: getIngress
  responses:
    '200':
      description: Ingress found
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Ingress.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '500':
      $ref: ../components/responses/500.yaml
put:
  summary: Update ingress
  description: Updates an existing money ingress
  operationId: updateIngress
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../components/schemas/IngressRequest.yaml
  responses:
    '200':
      description: Ingress updated successfully
      content:
        application/json:
          schema:
            $ref: ../components/schemas/Ingress.yaml
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '500':
      $ref: ../components/responses/500.yaml
delete:
  summary: Delete ingress
  description: Deletes a money ingress by ID
  operationId: deleteIngress
  responses:
    '204':
      description: Ingress deleted successfully
    '401':
      $ref: ../components/responses/401.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '500':
      $ref: ../components/responses/500.yaml
