SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE if exists proletariat_budget.accounts;
DROP TABLE if exists proletariat_budget.categories;
DROP TABLE if exists proletariat_budget.exchange_rates;
DROP TABLE if exists proletariat_budget.currencies;
DROP TABLE if exists proletariat_budget.expenditure_tags;
DROP TABLE if exists proletariat_budget.expenditures;
DROP TABLE if exists proletariat_budget.household_members;
DROP TABLE if exists proletariat_budget.ingress_recurrence_patterns;
DROP TABLE if exists proletariat_budget.ingress_tags;
DROP TABLE if exists proletariat_budget.ingresses;
DROP TABLE if exists proletariat_budget.roles;
DROP TABLE if exists proletariat_budget.savings_contribution_tags;
DROP TABLE if exists proletariat_budget.savings_contributions;
DROP TABLE if exists proletariat_budget.savings_goal_tags;
DROP TABLE if exists proletariat_budget.savings_goals;
DROP TABLE if exists proletariat_budget.savings_withdrawal_tags;
DROP TABLE if exists proletariat_budget.savings_withdrawals;
DROP TABLE if exists proletariat_budget.tags;
DROP TABLE if exists proletariat_budget.transaction_rollbacks;
DROP TABLE if exists proletariat_budget.transactions;
DROP TABLE if exists proletariat_budget.transfers;
DROP TABLE if exists proletariat_budget.user_roles;
DROP TABLE if exists proletariat_budget.users;
DROP TABLE if exists proletariat_budget.schema_migrations;
SET FOREIGN_KEY_CHECKS = 1;