openapi: 3.0.2
info:
  version: 1.0.0
  title: Proletariat Budget API
  contact: { }
paths:
  /auth/login:
    $ref: paths/login.yaml
  /auth/refresh:
    $ref: paths/token_refresh.yaml
  /auth/register:
    $ref: paths/register.yaml
  /expenditures:
    $ref: paths/expenditures.yaml
  /expenditures/{id}:
    $ref: paths/expenditures_{id}.yaml
  /expenditures/{id}/rollback:
    $ref: paths/expenditures_{id}_rollback.yaml
  /categories:
    $ref: paths/categories.yaml
  /categories/{id}:
    $ref: paths/categories_{id}.yaml
  /ingresses:
    $ref: paths/ingresses.yaml
  /ingresses/{id}:
    $ref: paths/ingresses_{id}.yaml
  /ingresses/{id}/rollback:
    $ref: paths/ingresses_{id}_rollback.yaml
  /recurrence-pattern:
    $ref: paths/recurrence-patterns.yaml
  /ingresses/{id}/recurrence-pattern/{pattern_id}:
    $ref: paths/ingresses_{id}_recurrence-patterns_{pattern_id}.yaml
  /accounts:
    $ref: paths/accounts.yaml
  /accounts/{id}:
    $ref: paths/accounts_{id}.yaml
  /transfers:
    $ref: paths/transfers.yaml
  /transfers/{id}:
    $ref: paths/transfers_{id}.yaml
  /transfers/{id}/rollback:
    $ref: paths/transfers_{id}_rollback.yaml
  /balances:
    $ref: paths/balances.yaml
  /exchange-rates:
    $ref: paths/exchange-rates.yaml
  /savings:
    $ref: paths/savings.yaml
  /transactions:
    $ref: paths/transactions.yaml
  /savings/{id}:
    $ref: paths/savings_{id}.yaml
  /savings/{id}/contributions:
    $ref: paths/savings_{id}_contributions.yaml
  /savings/{id}/withdrawals:
    $ref: paths/savings_{id}_withdrawals.yaml
  /savings/{id}/transactions:
    $ref: paths/savings_{id}_transactions.yaml
  /savings/{id}/progress:
    $ref: paths/savings_{id}_progress.yaml
  /household-members:
    $ref: paths/household-members.yaml
  /household-members/{id}:
    $ref: paths/household-members_{id}.yaml
  /tags:
    $ref: paths/tags.yaml
  /tags/{id}:
    $ref: paths/tags_{id}.yaml
  /tags/{type}:
    $ref: paths/tags_{type}.yaml

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: [ ]