type: object
properties:
  accountId:
    type: string
    description: The ID of the account this ingress belongs to
    example: acct_1234567890
  amount:
    type: number
    format: float
    description: The ingress amount
    example: 2500
  category:
    $ref: './Category.yaml'
  createdAt:
    type: string
    format: date-time
    description: The timestamp when the ingress was created
    example: '2023-04-15T12:34:56Z'
  source:
    type: string
    description: The source of the income
    example: Acme Corp
  description:
    type: string
    description: Additional details about the ingress
    example: Monthly salary payment
  tags:
    type: array
    items:
      $ref: './Tag.yaml'
    description: List of tag IDs associated with this ingress
    example:
      - id: tag_1234567890
        name: "Salary"
        color: "#FF0000"
        description: "Salary payment"
        backgroundColor: "#00FF00"
  date:
    type: string
    format: date
    description: The date of the ingress
    example: '2023-05-01'
  currency:
    type: string
    description: The currency of the ingress
    example: USD
  recurrencePattern:
    $ref: './RecurrencePattern.yaml'
required:
  - accountId
  - amount
  - category
  - date
  - currency
