type: object
properties:
  theme:
    type: string
    description: UI theme preference
    example: dark
  defaultCurrency:
    type: string
    description: Default currency for new transactions
    example: USD
  defaultExpensesCurrency:
    type: string
    description: Default currency for expenses
    example: USD
  defaultIngressesCurrency:
    type: string
    description: Default currency for ingresses
    example: USD
  timezone:
    type: string
    description: User's timezone in IANA format
    example: America/New_York
  dateFormat:
    type: string
    enum:
      - YYYY-MM-DD
      - MM/DD/YYYY
      - DD/MM/YYYY
      - DD.MM.YYYY
    description: Preferred date format
    example: YYYY-MM-DD
  numberFormat:
    type: string
    enum:
      - 1
      - 0
      - 1
      - 0
      - 1 000
      - 0
    description: Preferred number format
    example: 1,000.00
  language:
    type: string
    description: Preferred language (ISO 639-1 code)
    example: en
  budgetStartDay:
    type: integer
    minimum: 1
    maximum: 31
    description: Day of month when budget period starts
    example: 1
  weekStartDay:
    type: string
    enum:
      - monday
      - sunday
    description: First day of week for reports and views
    example: monday
  notificationsEnabled:
    type: boolean
    description: Whether to send notifications
    example: true
  notificationPreferences:
    type: object
    properties:
      email:
        type: boolean
        description: Whether to send email notifications
        example: true
      push:
        type: boolean
        description: Whether to send push notifications
        example: true
      budgetAlerts:
        type: boolean
        description: Alerts when approaching budget limits
        example: true
      savingsGoalUpdates:
        type: boolean
        description: Updates on savings goal progress
        example: true
required:
  - theme
  - defaultCurrency
  - timezone
