services:
  # Generate a mysql container
  mysql:
    image: mysql:8.0
    container_name: proletariat-budget-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: proletariat_budget
      MYSQL_USER: budgetuser
      MYSQL_PASSWORD: budgetpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "budgetuser", "-pbudgetpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    ulimits:
      nofile:
        soft: 262144
        hard: 262144